# Generated by Django 3.2.9 on 2021-12-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
